from openbabel import openbabel as ob

from isimo.constants import FRAGMENTS
from isimo.molutils import minimize


def detect_bonds(
    olig: ob.OBMol, atom_type1: str, atom_type2: str
) -> tuple[list[int], list[int]]:
    """
    Detect bonds between atoms named atom_type1 and atom_type2 in the molecule.
    Returns two parallel lists: indices of type1 atoms and indices of their matching type2 partners.
    Skips the terminal 5' and 3' edge cases.

    Parameters
    ----------
    olig : ob.OBMol
        An Open Babel molecule representing an oligonucleotide sequence.
    atom_type1 : str
        The name of the first atom type to search for (e.g., "O3'", "O5'").
    atom_type2 : str
        The name of the second atom type to search for (e.g., "C3'", "C5'").

    Returns
    -------
    tuple[list[int], list[int]]
        A pair of parallel lists:
        - The first list contains the atom indices of all atoms matching `atom_type1` that
          participate in a bond with `atom_type2`.
        - The second list contains the corresponding atom indices of the bonded partners
          matching `atom_type2`.
    """
    idxs_1: list[int] = []
    idxs_2: list[int] = []

    residues = sorted(list(ob.OBResidueIter(olig)), key=lambda r: r.GetNum())

    for current_res in residues:

        if (
            atom_type1 == "O3'"
            and atom_type2 == "C3'"
            and current_res.GetNum() == olig.NumResidues()
        ):
            continue
        if atom_type1 == "O5'" and atom_type2 == "C5'" and current_res.GetNum() == 1:
            continue

        for atom in ob.OBResidueAtomIter(current_res):
            atom_name = current_res.GetAtomID(atom)

            if atom_name.strip() == atom_type1:

                for neighbor in ob.OBAtomAtomIter(atom):

                    neighbor_res = neighbor.GetResidue()
                    neighbor_name = neighbor_res.GetAtomID(neighbor)

                    if neighbor_name.strip() == atom_type2:
                        idxs_1.append(atom.GetIdx())
                        idxs_2.append(neighbor.GetIdx())

    return idxs_1, idxs_2


def cut_bond(olig: ob.OBMol, idx1: int, idx2: int) -> list[ob.OBMol]:
    """
    Cuts a bond between specified atoms and returns two resulting fragments.

    Parameters
    ----------
    olig : ob.OBMol
        The original Open Babel molecule containing the bond to be cleaved.
    idx1 : int
        The index of the first atom forming the bond to cut (1-based OBMol index).
    idx2 : int
        The index of the second atom forming the bond to cut (1-based OBMol index).

    Returns
    -------
    list[ob.OBMol]
        A list of OBMol objects, each representing one of the molecular fragments
        generated by breaking the specified bond.
    """
    fragments = list()

    mol = ob.OBMol(olig)

    atom1, atom2 = mol.GetAtom(idx1), mol.GetAtom(idx2)

    mol.BeginModify()
    mol.DeleteBond(mol.GetBond(atom1, atom2))

    fragments.extend(mol.Separate())
    mol.EndModify()

    return fragments


def _delete_atoms_by_name(mol: ob.OBMol, residue: ob.OBResidue, names: set[str]):
    to_del = [
        atom
        for atom in ob.OBResidueAtomIter(residue)
        if residue.GetAtomID(atom).strip() in names
    ]
    for atom in to_del:
        mol.DeleteAtom(atom)


def _set_double_bond(mol, atom1, atom2):
    b = mol.GetBond(atom1, atom2) or mol.GetBond(atom2, atom1)
    if b:
        b.SetBondOrder(2)


def _add_H(frag, residue, o_name, h_name):

    for atom in ob.OBResidueAtomIter(residue):
        atom_name = residue.GetAtomID(atom).strip()
        if atom_name == o_name:
            o3_idx = atom.GetIdx()
            x0, y0, z0 = atom.GetX(), atom.GetY(), atom.GetZ()
    h_atom = frag.NewAtom()
    h_atom.SetAtomicNum(1)
    h_atom.SetVector(x0 + 1, y0, z0)
    residue.AddAtom(h_atom)
    residue.SetAtomID(h_atom, h_name)
    new_h_idx = h_atom.GetIdx()

    frag.AddBond(o3_idx, new_h_idx, 1)


def _modify_type_a(frag: ob.OBMol, residues, first_residue, last_residue):

    _delete_atoms_by_name(frag, last_residue, {"H4'"})
    c3, c4 = None, None
    for atom in ob.OBResidueAtomIter(last_residue):
        name = last_residue.GetAtomID(atom).strip()
        if name == "C3'":
            c3 = atom
        elif name == "C4'":
            c4 = atom
    _set_double_bond(frag, c3, c4)
    last_residue.SetName(last_residue.GetName().strip() + "a")

    return frag


def _modify_type_aB(frag: ob.OBMol, residues, first_residue, last_residue):

    _delete_atoms_by_name(frag, last_residue, {"H4'", "H2'"})
    c1, c2, c3, c4 = None, None, None, None
    for atom in ob.OBResidueAtomIter(last_residue):
        atom_name = last_residue.GetAtomID(atom).strip()
        if atom_name == "C4'":
            c4 = atom
        if atom_name == "C3'":
            c3 = atom
        if atom_name == "C2'":
            c2 = atom
        if atom_name == "C1'":
            c1 = atom
        if atom_name in {"N1", "N9"}:
            n = atom
    _set_double_bond(frag, c3, c4)
    _set_double_bond(frag, c1, c2)
    # print(c1, n)
    last_residue.SetName(last_residue.GetName().strip() + "v")

    bond = frag.GetBond(c1, n) or frag.GetBond(n, c1)
    # print(bond)
    if bond:
        frag.DeleteBond(bond)
    frag = frag.Separate()[0]

    return frag


def _modify_type_b(frag: ob.OBMol, residues, first_residue, last_residue):

    _add_H(frag, last_residue, "O3'", "HO3'")
    res3_name = last_residue.GetName().strip()
    if res3_name.endswith("H"):
        last_residue.SetName(res3_name[:-1] + "3")
    else:
        last_residue.SetName(res3_name + "3")

    return frag


def _modify_type_c(frag: ob.OBMol, residues, first_residue, last_residue):

    for atom in ob.OBResidueAtomIter(last_residue):
        last_residue.SetAtomID(
            atom, last_residue.GetAtomID(atom).strip() + "*"
        )  # Rename new atoms

    source_res = residues[-2]

    source_res.SetName(source_res.GetName().strip() + "c")
    last_residue.SetNum(source_res.GetNum())
    last_residue.SetName(source_res.GetName().strip())

    return frag


def _modify_type_d(frag: ob.OBMol, residues, first_residue, last_residue):

    _add_H(frag, last_residue, "O5'", "H")

    for atom in ob.OBResidueAtomIter(last_residue):
        last_residue.SetAtomID(
            atom, last_residue.GetAtomID(atom).strip() + "*"
        )  # Rename new atoms

    source_res = residues[-2]

    source_res.SetName(source_res.GetName().strip() + "d")
    last_residue.SetNum(source_res.GetNum())
    last_residue.SetName(source_res.GetName().strip())

    return frag


def _modify_type_w(frag: ob.OBMol, residues, first_residue, last_residue):

    _add_H(frag, first_residue, "O3'", "H")

    for atom in ob.OBResidueAtomIter(first_residue):
        first_residue.SetAtomID(
            atom, first_residue.GetAtomID(atom).strip() + "*"
        )  # Rename new atoms

        source_res = residues[1]

    source_res.SetName(source_res.GetName().strip() + "w")
    first_residue.SetNum(source_res.GetNum())
    first_residue.SetName(source_res.GetName().strip())

    return frag


def _modify_type_x(frag: ob.OBMol, residues, first_residue, last_residue):

    first_residue.SetName(first_residue.GetName().strip() + "x")

    return frag


def _modify_type_y(frag: ob.OBMol, residues, first_residue, last_residue):

    _add_H(frag, first_residue, "O5'", "HO5'")
    res5_name = first_residue.GetName().strip()
    if res5_name.endswith("H"):
        first_residue.SetName(res5_name[:-1] + "5")
    else:
        first_residue.SetName(res5_name + "5")

    return frag


def _modify_type_z(frag: ob.OBMol, residues, first_residue, last_residue):

    _delete_atoms_by_name(frag, first_residue, {"H4'"})
    c4, c5 = None, None
    for atom in ob.OBResidueAtomIter(first_residue):
        atom_name = last_residue.GetAtomID(atom).strip()
        if atom_name == "C4'":
            c4 = atom
        if atom_name == "C5'":
            c5 = atom
    _set_double_bond(frag, c4, c5)

    first_residue.SetName(first_residue.GetName().strip() + "z")

    return frag


def modify_fragment(frag: ob.OBMol, fragment_type: str) -> ob.OBMol:

    _MODIFIERS = {
        "a": _modify_type_a,
        "b": _modify_type_b,
        "c": _modify_type_c,
        "d": _modify_type_d,
        "w": _modify_type_w,
        "x": _modify_type_x,
        "y": _modify_type_y,
        "z": _modify_type_z,
        "a-B": _modify_type_aB,
    }
    residues = sorted(list(ob.OBResidueIter(frag)), key=lambda r: r.GetNum())
    first_residue = residues[0]
    last_residue = residues[-1]

    func = _MODIFIERS[fragment_type]

    frag.BeginModify()
    frag = func(frag, residues, first_residue, last_residue)

    frag = minimize(frag)

    return frag


def _process_fragment(fragment_name: str) -> tuple[str, int]:
    """
    Parse a fragment name into its text prefix and numeric suffix.
    """
    if fragment_name[:3] == "a-B":
        return fragment_name[:3], int(fragment_name[3:])
    return fragment_name[:1], int(fragment_name[1:])


def get_fragment(olig: ob.OBMol, fragment_name: str) -> ob.OBMol:
    """
    Reterns a specified fragment type from the provided oligonucleotide.

    Parameters
    ----------
    olig : ob.OBMol
        The original Open Babel molecule containing the bond to be cleaved.
    fragment_name: str

    Returns
    -------
    ob.OBMol
    """
    fragment_type, fragment_number = _process_fragment(fragment_name)

    idxs_1, idxs_2 = detect_bonds(olig, *FRAGMENTS[fragment_type])

    if fragment_number == 1:
        frag = modify_fragment(olig, fragment_type)
        return frag
    if fragment_type in "wxyz":
        fragments = cut_bond(
            olig,
            idxs_1[len(idxs_1) - fragment_number],
            idxs_2[len(idxs_1) - fragment_number],
        )
    else:
        fragments = cut_bond(
            olig, idxs_1[fragment_number - 1], idxs_2[fragment_number - 1]
        )

    if fragment_type in "wxyz":
        frag = fragments[1]
    else:
        frag = fragments[0]

    frag = modify_fragment(frag, fragment_type)

    return frag


def get_fragment_chirality(fragment_name: str, seq_linker: str) -> str:
    fragment_type, fragment_number = _process_fragment(fragment_name)
    new_linker = list("p" + seq_linker[1:].lower())

    if fragment_type in "wxyz":
        slice = new_linker[len(new_linker) - fragment_number + 1 :]
    else:
        slice = new_linker[:fragment_number]
    chirality = "".join(char for char in slice if char in ("s", "r"))
    return chirality


def main() -> None:
    pass
